<template>

  <div id="test">

    <NavigationDrawer id="n_bar" class="navDrawer_id" :items="pathway_info" @drawerSelector="drawerSetter" @pathSelection="updateCourse"></NavigationDrawer>

    <inquiryDisplay id="i_pan" class="inquiryDisplay_id" :items="specifiedCourse"></inquiryDisplay>

  </div>

</template>

<script>

import NavigationDrawer from './NavigationDrawer'
import inquiryDisplay from './inquiryDisplay'

export default {
  components: {
    NavigationDrawer,
    inquiryDisplay
  },
  data() {
    return {
      specifiedCourse: "asd1",
      drawerValue: false,
      pathway_info: [
        { name: "Minds and Machines", courseDescription: "This course is an introduction to the philosophy of mind and cognitive science. Students meet in small sections to have class discussions and debates about questions like: What are minds? Are minds physical or non-physical? Do humans have free will? Does reliance on technology turn humans into cyborgs? How close are humans to building an intelligent robot or machine? Do we want this to be a goal? Students will learn how make a philosophical argument, and how to express them in writing or through an oral presentation. This course is communication intensive", pathways: ["Artificial Intelligence", "Chinese Language", "History"] },
        { name: "AI and Society", courseDescription: "n/a", pathways: ["c1", "d1", "e2"] },
        { name: "Are Humans Rational?", courseDescription: "The Aristotelian dictum that we are rational animals is under severe attack these days. In fact, the previous sentence may seriously understate the situation: the dictum is perhaps outright rejected by many, if not most. From psychologists of reasoning and decision-making to behavioral economists to the “new atheists” (all groups whose message we will consider in this class), the onslaught is firmly underway, and fierce.", pathways: ["d", "e", "f"] },
        { name: "Introduction to Cognitive Science", courseDescription: "This course is an introduction to the new and quickly growing field of cognitive science. Cognitive Science is a highly interdisciplinary field of study of mind at the intersection of philosophy, psychology, computer science, neuroscience, linguistics, and anthropology. This is a communication-intensive course.", pathways: ["g", "h", "i"] },
        { name: "Cognitive Modeling", courseDescription: "Recent advances in Cognitive Science, Computer Science and Mathematics, have resulted in the ability to develop computer programs that implement Probabilistic Cognitive Models (PCMs). The cognitive models that this course covers are based on approximate Bayesian Inference implemented by Markov Chain Monte Carlo and Variational techniques that have made this approach tractable. The objective of this course is to enable the student to develop models of cognition in a Bayesian framework.", pathways: ["j", "k", "l"] },
        { name: "Programming for Cognitive Science and AI", courseDescription: "Research in Cognitive Science and Artificial Intelligence (AI) is driven by data. Researchers in these fields collect, manipulate, model and analyze data generated by real-world processes.  Since the amount of data available has grown exponentially, the ability to automate these tasks through computer programs is essential. Specifically, probabilistic and statistical computing are needed to learn from the data. The objectives of this course are for the student to perform exploratory data analysis and to acquire the basics of statistical and machine learning in order to model real-world datasets.", pathways: ["m", "n", "o"] },
        { name: "Game AI", courseDescription: "This course introduces students to basic concepts and methods of artificial intelligence and their applications in computer games. The topics include decision making, movement, path finding, and AI for human-like characters. This course will take the form of a combination of lectures, presentations by students, class discussions, and independent study.", pathways: ["p", "q", "r"] },
      ],
    }
  },
  methods: {
    updateCourse(course) {
      this.specifiedCourse = course;
      console.log(this.specifiedCourse.name)
    },
    drawerSetter(word) {
      if (word === "open") {
        this.drawerValue = false
        // nav bar
        document.getElementById("n_bar").style.float = "left";
        document.getElementById("n_bar").style.left = "7%"
        document.getElementById("n_bar").style.width = "20%"

        // course panel
        document.getElementById("i_pan").style.position = "absolute"
        document.getElementById("i_pan").style.left = "21%"
        document.getElementById("i_pan").style.width = "75%"

      }else if (word === "close") {
        this.drawerValue = true
        // nav panel
        document.getElementById("n_bar").style.float = "left";
        document.getElementById("n_bar").style.left = "10%"
        document.getElementById("n_bar").style.width = "20%"

        // course panel
        document.getElementById("i_pan").style.position = "absolute"
        document.getElementById("i_pan").style.left = "4%"
        document.getElementById("i_pan").style.width = "89%"

      }
    }
  },
}

</script>

<style>


  .navDrawer_id {
    float: left;
    left: 1%;
    width: 20%;
  }

  .inquiryDisplay_id {
    position: absolute;
    left: 21%;
    width: 77%;
  }



</style>
